# utils/pdf.py

import os
from datetime import datetime
from xml.sax.saxutils import escape

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def _safe_filename(label: str, year: int) -> str:
    """
    Make a filesystem-safe filename from the area label and target year.
    """
    if not label:
        label = "Selected_AOI"

    # Replace problematic characters so we don't accidentally create nested paths
    safe = (
        label.replace(" ", "_")
        .replace(",", "_")
        .replace("/", "_")
        .replace("\\", "_")
        .replace(":", "_")
        .replace(";", "_")
    )
    return f"TerraTrack_{safe}_{int(year)}.pdf"


def write_pdf(
    area_label: str,
    start_year: int,
    latest_year: int,
    target_year: int,
    summary_text: str,
) -> str:
    """
    Generate a nicely formatted PDF report.

    Parameters
    ----------
    area_label : str
        Human readable label for the AOI, e.g. "Surat, Gujarat, India".
    start_year : int
        Baseline year chosen by the user (e.g. 2010 or 2020).
    latest_year : int
        Latest observed year (usually baseline + 1 in your app).
    target_year : int
        Future projection year.
    summary_text : str
        The long layman summary generated by `render_summary(...)`.

    Returns
    -------
    str
        Absolute path to the generated PDF file.
    """

    # ------------------------------------------------------------------
    # 1. Output folder + filename
    # ------------------------------------------------------------------
    base_dir = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
    reports_dir = os.path.join(base_dir, "reports")
    os.makedirs(reports_dir, exist_ok=True)

    filename = _safe_filename(area_label, target_year)
    pdf_path = os.path.join(reports_dir, filename)

    # ------------------------------------------------------------------
    # 2. ReportLab document + styles
    # ------------------------------------------------------------------
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        title=f"TerraTrack AI — {area_label}",
        author="TerraTrack AI",
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TerraTitle",
        parent=styles["Title"],
        fontSize=20,
        leading=24,
        spaceAfter=10,
    )

    subtitle_style = ParagraphStyle(
        "TerraSubtitle",
        parent=styles["Normal"],
        fontSize=11,
        leading=14,
        textColor="#555555",
        spaceAfter=12,
    )

    section_heading_style = ParagraphStyle(
        "TerraSectionHeading",
        parent=styles["Heading2"],
        fontSize=13,
        leading=16,
        spaceBefore=6,
        spaceAfter=6,
    )

    body_style = ParagraphStyle(
        "TerraBody",
        parent=styles["BodyText"],
        fontSize=11,
        leading=14,
        spaceAfter=6,
    )

    # ------------------------------------------------------------------
    # 3. Build the story (content flow)
    # ------------------------------------------------------------------
    story = []

    # Main title
    story.append(Paragraph(f"TerraTrack AI — {escape(area_label)}", title_style))

    # Period + generation time
    period_line = (
        f"Period analysed: {int(start_year)} → {int(latest_year)} → "
        f"{int(target_year)} (projection)"
    )
    story.append(Paragraph(escape(period_line), subtitle_style))

    generated_on = datetime.now().strftime("%d %b %Y, %H:%M")
    story.append(
        Paragraph(
            escape(f"Report generated on: {generated_on} (local system time)"),
            styles["Normal"],
        )
    )

    # Small spacer before the actual content
    story.append(Spacer(1, 8 * mm))

    # Section heading for the layman part
    story.append(Paragraph("Layman Summary", section_heading_style))

    # Convert the plain-text summary into paragraphs.
    # We split on blank lines, escape HTML, and keep intra-paragraph line breaks.
    if summary_text:
        blocks = summary_text.split("\n\n")
        for block in blocks:
            block = block.strip()
            if not block:
                continue

            # Escape HTML special chars so ReportLab doesn't choke on "<" or "&"
            safe_block = escape(block)
            # Preserve user line breaks inside the block
            safe_block = safe_block.replace("\n", "<br/>")

            story.append(Paragraph(safe_block, body_style))

    # ------------------------------------------------------------------
    # 4. Build PDF
    # ------------------------------------------------------------------
    doc.build(story)

    return pdf_path
